source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'sinatra-cross_origin'
gem 'sqlite3'
gem 'rake'
gem 'bcrypt'
gem 'net-ldap', '~> 0.15.0'

group :development do
  gem 'puma'
  gem 'shotgun'
  gem 'faker'
end
